#admin_systeminfo:
#    path: /systeminfo
#    defaults:
#        _controller: ezsystems.platformui.controller.systeminfo:infoAction
#    methods: [GET]
#
#admin_phpinfo:
#    path: /systeminfo/phpinfo
#    defaults:
#        _controller: ezsystems.platformui.controller.systeminfo:phpinfoAction
#    methods: [GET]
