admin_systeminfo:
    path: /systeminfo
    defaults:
        _controller: ezsystems.systeminfo.controller.systeminfo:infoAction
    methods: [GET]

admin_phpinfo:
    path: /systeminfo/phpinfo
    defaults:
        _controller: ezsystems.systeminfo.controller.systeminfo:phpinfoAction
    methods: [GET]
