system:
    default:
        yui:
            modules:
                ezconf-sysinfoappplugin:
                    requires: ['ez-pluginregistry', 'plugin', 'base', 'ezconf-sysinfoview', 'ezconf-sysinfoviewservice'] # depends on the plugin code
                    dependencyOf: ['ez-platformuiapp']
                    path: %system_info.public_dir%/js/apps/plugins/ezconf-sysinfoappplugin.js
                ezconf-navigationplugin:
                    requires: ['ez-pluginregistry', 'ez-viewservicebaseplugin', 'ez-navigationitemview']
                    dependencyOf: ['ez-navigationhubviewservice']
                    path: %system_info.public_dir%/js/views/services/plugins/ezconf-navigationplugin.js
                ezconf-sysinfoviewservice:
                    requires: ['ez-serversideviewservice']
                    path: %system_info.public_dir%/js/views/services/ezconf-sysinfoviewservice.js
                ezconf-sysinfoview:
                    requires: ['ez-serversideview']
                    path: %system_info.public_dir%/js/views/ezconf-sysinfoview.js
